### ISSUE TITLE
Shortwave band frequency save

### ISSUE THREAD

**Issue by Berry2525** [goshante/ats20_ats_ex#12]
I hope that when switching the shortwave band, the frequency of the current band can be saved, so that if you switch the band back and forth, you can listen to it at the previous frequency, just like the original firmware，Thank you！

**Comment by goshante** [comment]
This will not be implemented because now SW is the only band. It has multiple sub-bands that work like bookmarks. In earlier versions, each sub-band existed as a dedicated band. As a regular band, each SW segment could save the recent frequency for each segment.

This is a bad implementation because:

Scrolling between bands assumes you can easily access the desired frequency. So, you switch to the nearest one and quickly tune to the nearest frequency. If you saved 5200 frequency for the 4500 band and you want to access the 4100 frequency, you have to scroll more than 1 MHz to reach the desired frequency. This is inconvenient.
If you stopped on the 3000 band and manually tuned to 15000 KHz, 15000 will be saved to the 3000 band. This requires extra code to fix it. Reworking the band logic requires reimplementation, optimization, and removal of some elements, which I don't want to do.
The current implementation saves more flash space. A single SW band has only one frequency to save, but when you move out of the SW band without touching the tuning knob, your last frequency will be saved to SW, allowing you to access it again later.
