### ISSUE TITLE
is it true if in the ats settings I will select cpu 50% it will reduce the interference or not?

### ISSUE THREAD

**Issue by ShasaLegend** [goshante/ats20_ats_ex#22]
i have switched to different bands and frequencies but nothing has changed but I'm not sure

**Comment by G8PTN** [comment]
Hi,
Reducing the CPU speed to 50% divides the internal system clock by a factor of two.
Everything will work at half speed, including screen updates and other external IO transactions.
This may or may not change RFI noise on some bands.

For example, the standard I2C clock speed is 100kHz.
- At 100% CPU speed, peaks will occur at 100kHz, 300kHz, 500kHz etc.
- At 50% CPU speed, peaks will occur at 50kHz, 150kHz, 250kHz etc.
- Therefore when writing/reading the I2C interface RFI  noise may be detected at these frequencies.

The current consumption of the processor will be reduced when operating at 50% CPU speed, but this may only be a small decrease in reality, since the display, radio IC and audio amplifier will all be contributing to the overall consumption.
73, Dave
