### ISSUE TITLE
Can you say what is the best ats 20 plus settings for the best reception in any situation the best settings?

### ISSUE THREAD

**Issue by ShasaLegend** [goshante/ats20_ats_ex#23]
i have bad reception or bad semnal
i need 
ATT,SM,SVC,DeE,AVC,SSM,COF

**Comment by G8PTN** [comment]
Hi,
In my experience, the default settings seem to work well.
I did change ATT from “AUT” to “1”, which removes the slight background noise in SSB modes. This is covered in the manual and does not really need to be changed.

![Att](https://github.com/user-attachments/assets/79d95675-970f-4777-bbfb-57549613379a)

All the configuration options are available for the user to adjust if required. There will not necessarily be a single optimum setting for all conditions.
73, Dave

**Comment by ShasaLegend** [comment]
yes i know the default settings are good but with ATT i have problems 
but the SM,SSM,AVC is better to set the default or change it?
in setting SM stay 0
SSM stay SNR
AVC stay 60

**Comment by ShasaLegend** [comment]
yes i know the default settings are good but with ATT i have problems 
but the SM,SSM,AVC is better to set the default or change it?
in setting SM stay 0
SSM stay SNR
AVC stay 60
and IF signal comes out from ats?

**Comment by G8PTN** [comment]
Hi,
I would expect that the default settings used in the Goshante firmware match those recommended by the PU2CLR SI473x library.

There is no IF output from the ATS-20. The demodulation is done digitally in the SI473x receiver chip.

As previously stated, the optimum settings will probably vary depending on band, mode, antenna, user preference etc.

ATT
Increasing the attenuation level might be useful under strong signals conditions, but there is no front-end filtering so overload from out of band signals will always be a problem.
 
SM		Soft Mute
SSM		SSB Soft Mute
The soft mute only really affects the tuning experience. This was mainly noticeable in SSB.
With the Goshante firmware it is much less of a problem because of the tuning method used.
![ATS20_EX](https://github.com/user-attachments/assets/31166650-87b4-4307-8b38-f298d832b3ca)

AVC		Automatic Volume Control
SVC		Enable AVC for SSB
The AVC might be useful for weak signals, but it will also increase the level of the noise.
73, Dave

**Comment by G8PTN** [comment]
Hi,
If AVC set to 60 works better for you, then leave it at that.
73, Dave

**Comment by ShasaLegend** [comment]
ok thanks have a nice day
