### ISSUE TITLE
Hi is it possible to make a mini update of that firmware in the update, I would like that when the Search function is turned off in the settings, then when you press the button on the encoder not to change the step, but to change the BFO, it will be more convenient that way.
Thanks

### ISSUE THREAD

**Issue by ShasaLegend** [goshante/ats20_ats_ex#25]

**Comment by G8PTN** [comment]
Hi,
My understanding is that the author of the firmware (goshante) is busy on other commitments and does not plan updates at the moment.

When tuning in SSB mode, the tuning mechanism automatically uses the BFO as described below.
![Tuning](https://github.com/user-attachments/assets/99acf535-186c-4885-8b50-e57bfb46c7ab)

The BFO adjustment in the settings menu is to allow an offset to be made for calibration so that the receivers displayed frequency matches a known frequency standard.
![BFO](https://github.com/user-attachments/assets/5773abce-6e9a-4f85-aae1-850a690d84c6)

73, Dave

**Comment by ShasaLegend** [comment]
Hi yes i understand but it was better when is SSB or the encoder button to change BFO
but if you have the sketch in ino can you please send i want to change that code for me to modify.
Thanks

**Comment by G8PTN** [comment]
Hi,
The code is already available in the github.
https://github.com/goshante/ats20_ats_ex/tree/master/ATS_EX
73, Dave

**Comment by ShasaLegend** [comment]
what is that library font14×24sevenSeg.h?

**Comment by G8PTN** [comment]
Hi,
I assume it is used for the frequency display as stated in the user manual.
73, Dave

![image](https://github.com/user-attachments/assets/21730338-0eec-4090-a2ed-9a09e8b2bdb9)

**Comment by tormoz108** [comment]
tmp

**Comment by tormoz108** [comment]
Гораздо лучше, чем енять шаг настройки сделать его переменным. При быстром вращении крутилки *10 при замедлении - возвращать к нормальному. При смене направления вращения - так же возвращать к норме. Для переключения использовать гистерезис.

**Comment by tormoz108** [comment]
uint16_t midEconderTikTime;
bool g_lastseekDirection;    // куда крутили до этого
byte n;                  // коэффициент ускорения кручения
byte swithD;               //  туда сюда

void doFrequencyTune()
{
  if (g_displayOn)
  {

    g_seekDirection = g_encoderCount == 1 ? 1 : 0;
    //  if ( EconderTikTime > 270) midEconderTikTime += 20;
    EconderTikTime = (millis() - g_lastFreqChange);   //sid
    //  midEconderTikTime = midEconderTikTime>>1 +  midEconderTikTime>>2 + EconderTikTime>>2;  // сглаживающий фильтр
    midEconderTikTime = midEconderTikTime / 2 +  midEconderTikTime / 4 + EconderTikTime / 4; // сглаживающий фильтр
    //   if (EconderTikTime < 250)

    if (midEconderTikTime < 200) n = 10;   //ускорение крутилки

    if ( midEconderTikTime > 350) n = 1;

    if ( g_lastseekDirection != g_seekDirection)
    {
      n = 1;
      midEconderTikTime = 500;
    }


    if (g_currentMode == FM)
    {
      g_currentFrequency += g_tabStepFM[g_FMStepIndex] * g_encoderCount

**Comment by G8PTN** [comment]
Hi,
Yes, accelerated tuning can be advantageous.
There are probably several different options that could be added, but many are perhaps user specific.
I decided to add Bluetooth control, so that I can try customising options via an App.
Good luck with any changes.
73, Dave
![image](https://github.com/user-attachments/assets/978f5a91-ad06-47dd-a4ff-b5c17fcce498)

**Comment by ShasaLegend** [comment]
for me i just want waterfall and dbm sensibility show and that's it, can you please show me how to make that app wia cable connection

**Comment by G8PTN** [comment]
Hi,
I have no plans to release the code. It only provides basic serial monitoring/control.
The principle was shown in this thread.
https://github.com/goshante/ats20_ats_ex/issues/7#issuecomment-2308964134
If you want to have a waterfall, I suggest you look at something like the ATS-25, which uses the same radio IC, but has a more powerful MCU.
73, Dave
