### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by ShasaLegend** [goshante/ats20_ats_ex#28]
Does Si4732 have a IFIN?
i want to use a panadapter to my ats 20 plus

**Comment by G8PTN** [comment]
Hi,
I am not sure if you mean IFOUT?
There is no IF output from the SI473x.
![image](https://github.com/user-attachments/assets/0144a0ee-a4f4-4487-b7e5-150fd7113d1e)

73, Dave

**Comment by ShasaLegend** [comment]
Hi,i mean IFIN where if brut in entering in the si4732 i want to make a panadapter for ats

**Comment by G8PTN** [comment]
Hi,
Normally a panadapter needs a tap from the IF stage of the receiver, which can not be done with the Si4732.
You could use an RF splitter and something like an RTL-SDR dongle, but you may as well then use the dongle as the receiver rather than the ATS-20.
Please could you show a diagram of what you are trying to achieve.
73, Dave

**Comment by ShasaLegend** [comment]
thanks

**Comment by ShasaLegend** [comment]
no i dont have a diagram or a circuit i want to try but if it is not IFin i will not try
